version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: planmind-postgres
    environment:
      POSTGRES_DB: planmind
      POSTGRES_USER: planmind
      POSTGRES_PASSWORD: planmind123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planmind-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U planmind" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: planmind-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - planmind-network
    command: redis-server --appendonly yes

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: planmind-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=planmind
      - DB_USER=planmind
      - DB_PASSWORD=planmind123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - planmind-network

volumes:
  postgres_data:
  redis_data:

networks:
  planmind-network:
    driver: bridge