version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: planmind-postgres
    environment:
      POSTGRES_DB: planmind
      POSTGRES_USER: planmind
      POSTGRES_PASSWORD: planmind123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planmind-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U planmind" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: planmind-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=planmind
      - DB_USER=planmind
      - DB_PASSWORD=planmind123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - planmind-network

volumes:
  postgres_data:

networks:
  planmind-network:
    driver: bridge